# Generated by Django 3.1.5 on 2022-11-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20221129_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=122, null=True, verbose_name='Name'),
        ),
    ]
