# Generated by Django 3.1.5 on 2022-12-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_blog_exerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('active', 'active')], default='pending', max_length=20),
        ),
    ]
