# Generated by Django 3.1.5 on 2022-12-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20221210_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('active', 'active')], default='active', max_length=20),
        ),
    ]
