# Generated by Django 3.1.5 on 2022-12-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20221210_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
