# Generated by Django 3.1.5 on 2022-12-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_blog_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
