# Generated by Django 3.1.5 on 2022-12-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_blog_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsignup',
            options={'verbose_name_plural': 'User Emails'},
        ),
    ]
